### ISSUE TITLE
Belt wall flow saves as 150% in settings overview

### ISSUE THREAD

**Issue by riktheunissen** [BlackBelt3D/Cura#13] opened 2018-09-12 14:33 UTC
**Application Version**
3.4.3

**Platform**
Windows

**Printer**
BlackBelt 3D

**Steps to Reproduce**
saved multiple gcodes with different flow rates and different gantry angles

**Actual Results**
Always saves as 150% belt wall flow 

**Expected results**
Expect it to save the value entered in Cura

**Additional Information**
![beltwallflow](https://user-images.githubusercontent.com/42371563/45432172-7eed2880-b6a9-11e8-8aae-ba69e2cf3e67.JPG)

**Comment by fieldOfView** [comment] 2018-09-28 14:04
I can't reproduce this with the BB Cura 3.5 beta.

@BBStephan, can I have your second opinion?

**Comment by fieldOfView** [comment] 2018-09-28 14:04
Fee free to reopen if you can reproduce it.

**Comment by BBStephan** [comment] 2018-09-28 14:07
I can not reproduce it ad well 
![image](https://user-images.githubusercontent.com/32984892/46213342-37fd6500-c330-11e8-8fdd-7941d70405b3.png)

**Comment by BBStephan** [comment] 2018-10-02 14:49
We can reproduce it with PLA only.

**Comment by fieldOfView** [comment] 2018-10-03 07:50
Confirmed. I'll work on a fix.

**Comment by fieldOfView** [comment] 2018-10-08 14:57
Fixed in #e5eef67

**Closed** 2018-10-08 17:49 UTC
Labels: bug
